# Generated by Django 6.0.2 on 2026-03-30 23:11
# No-op: OtpChallenge is created in 0002_otp_challenge; duplicate CreateModel broke migrate.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id'),
    ]

    operations = []
