# Generated by Django 6.0.2 on 2026-04-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_id'),
        ('users', '0003_merge_20260331'),
    ]

    operations = [
    ]
