# Generated by Django – email_verified for password-reset gating

from django.db import migrations, models


def set_existing_users_verified(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    CustomUser.objects.all().update(email_verified=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_0003_alter_customuser_id_0003_merge_20260331"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_existing_users_verified, noop_reverse),
    ]
