# Generated by Django 6.0.2 on 2026-04-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp_challenge'),
        ('users', '0006_customuser_social_urls'),
    ]

    operations = [
    ]
