# Generated by Django 6.0.2 on 2026-04-14 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_confirmation', models.BooleanField(default=True)),
                ('transaction_edited', models.BooleanField(default=False)),
                ('transaction_invoice', models.BooleanField(default=True)),
                ('transaction_cancelled', models.BooleanField(default=True)),
                ('transaction_refund', models.BooleanField(default=True)),
                ('payment_error', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification preferences',
            },
        ),
    ]
