# Generated by Django 6.0.2 on 2026-04-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('property_alert', 'Property alert'), ('expired', 'Expired'), ('message', 'Message')], db_index=True, max_length=32),
        ),
    ]
