# Generated by Django 6.0.2 on 2026-04-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_message_and_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_conversation_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='For message-type alerts: conversation id; cleared when recipient opens the thread.', null=True),
        ),
    ]
