# Generated by Django 6.0.2 on 2026-04-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
        ('notifications', '0004_alter_notification_related_conversation_id'),
    ]

    operations = [
    ]
