# Generated by Django 6.0.2 on 2026-04-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_merge_20260417_2206'),
        ('notifications', '0005_merge_notification_branches'),
    ]

    operations = [
    ]
