"""
Django settings for home_backend_site project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eyqrmo2ib0q9jyu#(1%$_fc5mu3nb9h-c%_%2r620(sjlc=(+('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #THIRD PARTY APPS
    'rest_framework',
    'corsheaders',
    #this filter helps me to preview all fields when i run the backend server 
    'django_filters',
    'drf_spectacular',
    #LOCAL APPS
    'users',
    'properties',
    'messaging',
    'notifications',
    'bookings',
]

MIDDLEWARE = [
    # CORS HEADERS TO ALLOW REQUEST FROM REACT FRONTEND 
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    #DEFAULT MIDDLEWARES
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'home_backend_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'home_backend_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, images, JavaScript)
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email (OTP / password reset). Console backend prints messages when DEBUG is True.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@estatery.local'

# Default primary key field type to use custom user model
AUTH_USER_MODEL = 'users.CustomUser'

# Create media folder
import os
os.makedirs(MEDIA_ROOT, exist_ok=True)


# For development - allow all origins (change in production)
CORS_ALLOW_ALL_ORIGINS = True


# Option A: Allow specific origins (recommended for production)
#CORS_ALLOWED_ORIGINS = [
#   "http://localhost:3000",
#   "https://yourfrontend.com",
#]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Estatery / Home Backend API',
    'DESCRIPTION': (
        'REST API for the Estatery property rental platform: authentication (JWT), '
        'listings, bookings, payments, reviews, dashboards, promos, and public catalog endpoints.'
    ),
    'VERSION': '1.0.0',
    'CONTACT': {'name': 'API Support'},
    'LICENSE': {'name': 'Proprietary'},
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api',
    'TAGS': [
        {
            'name': 'Auth',
            'description': (
                'Registration, login, profile, JWT refresh, password reset (OTP), '
                'and generic OTP request/verify.'
            ),
        },
        {'name': 'Properties', 'description': 'Listings, detail, host "my properties"'},
        {'name': 'Customer catalog', 'description': 'Public customer-facing listing route'},
        {'name': 'Geography', 'description': 'Countries and related facets'},
        {'name': 'Discounts', 'description': 'Promo validation and admin promo CRUD'},
        {'name': 'Availability', 'description': 'Calendar and availability checks'},
        {'name': 'Bookings', 'description': 'Tenant bookings'},
        {'name': 'Host', 'description': 'Host booking management'},
        {'name': 'Payments', 'description': 'Booking payments and mark-paid'},
        {'name': 'Reviews', 'description': 'Property reviews and host responses'},
        {'name': 'Dashboards', 'description': 'Host and tenant summaries'},
    ],
    'SECURITY': [{'bearerAuth': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayOperationId': False,
        'filter': True,
        'persistAuthorization': True,
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # Used when client sends remember_me / keep_logged_in on login
    'REFRESH_TOKEN_LIFETIME_REMEMBER': timedelta(days=30),
}