"""
Django settings for home_backend_site project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eyqrmo2ib0q9jyu#(1%$_fc5mu3nb9h-c%_%2r620(sjlc=(+('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #THIRD PARTY APPS
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    #this filter helps me to preview all fields when i run the backend server 
    'django_filters',
    #LOCAL APPS
    'users',
    'properties',
    'bookings',
    'messaging',
    'notifications',
]

MIDDLEWARE = [
    # CORS HEADERS TO ALLOW REQUEST FROM REACT FRONTEND 
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    #DEFAULT MIDDLEWARES
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'home_backend_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'home_backend_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, images, JavaScript)
STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email (OTP / password reset).
# Without EMAIL_HOST: console backend — OTP prints in the runserver terminal only.
# With EMAIL_HOST: SMTP. Put values in backend/home_backend/.env (see .env.example).
#   Port 587 + STARTTLS: EMAIL_USE_TLS=true, EMAIL_USE_SSL=false (default).
#   Port 465 + implicit SSL: EMAIL_USE_SSL=true, EMAIL_PORT=465, EMAIL_USE_TLS=false.
_email_host = os.environ.get("EMAIL_HOST", "").strip()
if _email_host:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = _email_host
    EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "false").lower() in (
        "1",
        "true",
        "yes",
    )
    if EMAIL_USE_SSL:
        EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "465"))
        EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "false").lower() in (
            "1",
            "true",
            "yes",
        )
    else:
        EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
        EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in (
            "1",
            "true",
            "yes",
        )
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    DEFAULT_FROM_EMAIL = os.environ.get(
        "DEFAULT_FROM_EMAIL",
        EMAIL_HOST_USER or "noreply@estatery.local",
    )
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "noreply@estatery.local"

# Default primary key field type to use custom user model
AUTH_USER_MODEL = 'users.CustomUser'

# Create media folder
os.makedirs(MEDIA_ROOT, exist_ok=True)


# For development - allow all origins (change in production)
CORS_ALLOW_ALL_ORIGINS = True


# Option A: Allow specific origins (recommended for production)
#CORS_ALLOWED_ORIGINS = [
#   "http://localhost:3000",
#   "https://yourfrontend.com",
#]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Estatery / Home Backend API',
    'DESCRIPTION': (
        'REST API for the Estatery property rental platform: authentication (JWT, refresh), '
        'password reset with OTP, generic OTP, listings, bookings, payments, reviews, '
        'host/tenant dashboards, promo codes, and public/customer catalog endpoints.'
    ),
    'VERSION': '1.0.0',
    'CONTACT': {'name': 'API Support'},
    'LICENSE': {'name': 'Proprietary'},
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api',
    'TAGS': [
        {'name': 'Auth', 'description': 'Registration, login, profile, JWT refresh, password reset, OTP'},
        {'name': 'Properties', 'description': 'Listings, detail, host "my properties"'},
        {'name': 'Customer catalog', 'description': 'Public customer-facing listing route'},
        {'name': 'Reference', 'description': 'Lookup data (e.g. currency codes)'},
        {'name': 'Geography', 'description': 'Countries and related facets'},
        {'name': 'Discounts', 'description': 'Promo validation and admin promo CRUD'},
        {'name': 'Availability', 'description': 'Calendar and availability checks'},
        {'name': 'Bookings', 'description': 'Tenant bookings'},
        {'name': 'Host', 'description': 'Host booking management'},
        {'name': 'Payments', 'description': 'Booking payments and mark-paid'},
        {'name': 'Reviews', 'description': 'Property reviews and host responses'},
        {'name': 'Dashboards', 'description': 'Host and tenant summaries'},
        {'name': 'Notifications', 'description': 'In-app notifications (badge, list, mark read)'},
    ],
    'SECURITY': [{'bearerAuth': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayOperationId': False,
        'filter': True,
        'persistAuthorization': True,
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}