# Generated by Django 6.0.2 on 2026-02-13 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Description')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('villa', 'Villa'), ('studio', 'Studio')], max_length=20)),
                ('daily_price', models.DecimalField(decimal_places=2, help_text='Price per night', max_digits=10, verbose_name='Daily price')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per month (optional - will auto-calculate from daily if blank)', max_digits=10, null=True, verbose_name='Monthly price')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(default=1, verbose_name='Bedrooms')),
                ('bathrooms', models.IntegerField(default=1, verbose_name='Bathrooms')),
                ('area', models.IntegerField(verbose_name='Area (sq ft)')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Parking')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Pool')),
                ('has_gym', models.BooleanField(default=False, verbose_name='Gym')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Furnished')),
                ('has_kitchen', models.BooleanField(default=True, verbose_name='Kitchen')),
                ('min_stay_months', models.PositiveIntegerField(default=12, help_text='Minimum booking period in months', verbose_name='Minimum stay (months)')),
                ('max_stay_months', models.PositiveIntegerField(blank=True, help_text='Maximum booking period in months (optional)', null=True, verbose_name='Maximum stay (months)')),
                ('monthly_cycle_start', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28)], default=1, help_text='Day of month when rentals start (1-28)', verbose_name='Monthly cycle start day')),
                ('security_deposit_months', models.DecimalField(decimal_places=1, default=2.0, help_text='Number of months rent required as deposit', max_digits=3, verbose_name='Security deposit (months)')),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.IntegerField(default=1)),
                ('booking_type', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], default='monthly', max_length=20)),
                ('agreed_monthly_rate', models.DecimalField(decimal_places=2, help_text='Monthly rate at time of booking', max_digits=10, verbose_name='Agreed monthly rate')),
                ('months_booked', models.PositiveIntegerField(default=1, help_text='Number of months booked')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, help_text='Security deposit amount', max_digits=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage applied', max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('special_requests', models.TextField(blank=True)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_refunded', models.BooleanField(default=False)),
                ('deposit_refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('property_rented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1-5')),
                ('comment', models.TextField()),
                ('host_response', models.TextField(blank=True)),
                ('host_responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='properties.booking')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('deposit', 'Security Deposit'), ('rent', 'Monthly Rent'), ('late_fee', 'Late Fee'), ('utility', 'Utilities'), ('damage', 'Damage Fee'), ('refund', 'Refund')], default='rent', max_length=20)),
                ('month_number', models.PositiveIntegerField(help_text='Month number (0 for deposit, 1-12 for rent)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.booking')),
            ],
            options={
                'ordering': ['due_date', 'month_number'],
                'indexes': [models.Index(fields=['booking', 'status', 'due_date'], name='properties__booking_2dad89_idx'), models.Index(fields=['due_date', 'status'], name='properties__due_dat_2dd409_idx')],
                'unique_together': {('booking', 'month_number', 'payment_type')},
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'city', 'country'], name='properties__status_12233b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'status'], name='properties__owner_i_30ec29_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['property_rented', 'check_in', 'check_out', 'status'], name='properties__propert_75e8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status', '-created_at'], name='properties__user_id_e141d8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['property_rented', 'status', 'check_in'], name='properties__propert_5e1338_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='check_out_after_check_in'),
        ),
        migrations.AddIndex(
            model_name='propertyreview',
            index=models.Index(fields=['property', '-created_at'], name='properties__propert_ee1663_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreview',
            index=models.Index(fields=['user', '-created_at'], name='properties__user_id_ad89d3_idx'),
        ),
    ]
