# Generated by Django 6.0.2 on 2026-03-26 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_listing_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percent (0–100) or fixed amount in listing currency', max_digits=10)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited uses', null=True)),
                ('times_redeemed', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('min_booking_months', models.PositiveIntegerField(blank=True, help_text='Minimum months booked to use this code', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo code',
                'verbose_name_plural': 'Promo codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='properties__propert_75e8ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='properties__propert_5e1338_idx',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='property_rented',
            new_name='rented_property',
        ),
        migrations.AddField(
            model_name='promocode',
            name='applies_to_property',
            field=models.ForeignKey(blank=True, help_text='Limit to one property; leave empty for all listings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='properties.property'),
        ),
        migrations.AddField(
            model_name='booking',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='properties.promocode'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['rented_property', 'check_in', 'check_out', 'status'], name='properties__rented__da1b95_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['rented_property', 'status', 'check_in'], name='properties__rented__bce4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code', 'is_active'], name='properties__code_37b8a2_idx'),
        ),
    ]
