# Generated by Django 5.2.11 on 2026-03-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_booking_id_alter_bookingpayment_id_and_more'),
        ('properties', '0004_promocode_and_more'),
    ]

    operations = [
    ]
