# Generated by Django 6.0.2 on 2026-04-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_booking_id_alter_bookingpayment_id_and_more'),
        ('properties', '0006_rename_booking_fk_sqlite_column'),
    ]

    operations = [
    ]
